### PR TITLE
Prepare for migration for LPWebQuery and insert script to calabash-ios-server

### PR DESCRIPTION
**Pull request by jmoody**
Hey Karl,

This is what I would do to get the LPWebQuery sources into calabash-ios-server.

Ultimately, I would add a calabash-ios-server `make` rule:

```
$ make web-headers
```

With these changes, this repo becomes very tiny.  Are you sure we cannot just move it all the calabash-ios-server?

### CODE REVIEW

**Comment by krukow** [comment]
@jmoody LGTM -- we can't move the JavaScript into calabash-ios-server as it is shared with Calabash Android

**Comment by krukow** [comment]
@jmoody is there a corresponding calabash-ios-server pr?

**Comment by jmoody** [comment]
Thanks for looking @krukow 

> we can't move the JavaScript into calabash-ios-server as it is shared with Calabash Android

Got it.

> is there a corresponding calabash-ios-server pr?

There is no corresponding server PR yet.  I am working on it.

I have the `webquery_headers` implemented and tested.

Maybe I will commit that before I start pounding on the LPWebQuery for WKWebViews so you can see what I have in mind.

**WKWebView support for Calabash iOS?** [#calabash-ios/707](https://github.com/calabash/calabash-ios/issues/707)

**Comment by krukow** [comment]
@jmoody sounds great. Go ahead and merge this

**Pull request merged**
